num1 = (input("Put 1 number : "))
num2 = (input("Put one more number : "))
print(num1,"+", num2, "=", int(num1) + int(num2))
print(num1,"-", num2, "=", int(num1) - int(num2))
print(num1,"*", num2, "=", int(num1)*int(num2))
print(num1,"/", num2, "=", int(num1)/int(num2))